import { PDFDocument, rgb, StandardFonts } from 'npm:pdf-lib@1.17.1';
import type { SupabaseClient } from 'npm:@supabase/supabase-js@2';

function dealTypeLabel(dealType: string | null): string {
  const map: Record<string, string> = {
    sale: 'Sale / Mechirah',
    rent: 'Rent / Haskarah',
    exclusive: 'Exclusive',
  };
  return map[dealType || ''] || dealType || '—';
}

function agreementTypeLabel(t: string | null): string {
  const map: Record<string, string> = {
    exclusive: 'Exclusive',
    open: 'Open',
    mediation: 'Mediation',
  };
  return map[t || ''] || t || '—';
}

export async function buildAgreementPdfBytes(
  link: Record<string, unknown>,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  let y = height - 50;

  const draw = (text: string, size = 11, bold = false) => {
    page.drawText(text, {
      x: 50,
      y,
      size,
      font: bold ? fontBold : font,
      color: rgb(0.15, 0.15, 0.2),
      maxWidth: width - 100,
    });
    y -= size + 8;
  };

  page.drawRectangle({
    x: 0,
    y: height - 70,
    width,
    height: 70,
    color: rgb(0.23, 0.51, 0.96),
  });
  page.drawText('NexEstate — Signed Agreement', {
    x: 50,
    y: height - 42,
    size: 18,
    font: fontBold,
    color: rgb(1, 1, 1),
  });
  y = height - 100;

  draw('Agreement Confirmation', 14, true);
  y -= 6;

  const rows: [string, string][] = [
    ['Client', String(link.client_name || '—')],
    ['Phone', String(link.client_phone || '—')],
    ['Email', String(link.client_email || '—')],
    ['ID', String(link.signer_id_number || '—')],
    ['Deal type', dealTypeLabel(link.deal_type as string | null)],
    ['Agreement', agreementTypeLabel(link.agreement_type as string | null)],
    ['Property', String(link.property_description || link.exact_address || '—')],
    ['Address', String(link.exact_address || link.property_address || '—')],
    ['Price', link.price != null ? String(link.price) : '—'],
    [
      'Commission',
      link.commission_percent != null ? `${link.commission_percent}%` : '—',
    ],
    ['Broker', String(link.broker_name || '—')],
    ['Signed at', String(link.signed_at || new Date().toISOString())],
    ['Ref', String(link.token || '—').slice(0, 24)],
  ];

  for (const [label, value] of rows) {
    draw(`${label}: ${value}`, 11);
  }

  const sig = link.signature_data as { image?: string } | string | null;
  const imageData =
    typeof sig === 'string'
      ? sig
      : sig && typeof sig === 'object'
        ? sig.image
        : null;

  if (imageData && typeof imageData === 'string' && imageData.includes('base64,')) {
    try {
      const b64 = imageData.split('base64,')[1];
      const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
      const png = await doc.embedPng(bytes).catch(() => null);
      const jpg = png ? null : await doc.embedJpg(bytes).catch(() => null);
      const img = png || jpg;
      if (img) {
        y -= 10;
        draw('Signature:', 12, true);
        const maxW = 220;
        const scale = Math.min(maxW / img.width, 80 / img.height);
        page.drawImage(img, {
          x: 50,
          y: Math.max(40, y - img.height * scale),
          width: img.width * scale,
          height: img.height * scale,
        });
      }
    } catch (e) {
      console.warn('Could not embed signature image', e);
    }
  }

  page.drawText('Generated by NexEstate digital signing', {
    x: 50,
    y: 30,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.55),
  });

  return doc.save();
}

/** Build PDF, upload to signed-contracts, update pdf_url. Returns signed URL. */
export async function generateAndStoreAgreementPdf(
  supabase: SupabaseClient,
  link: Record<string, unknown>,
): Promise<string | null> {
  const id = String(link.id);
  const pdfBytes = await buildAgreementPdfBytes(link);
  const brokerFolder = String(link.broker_id || 'public');
  const path = `${brokerFolder}/${id}.pdf`;

  const { error: uploadError } = await supabase.storage
    .from('signed-contracts')
    .upload(path, pdfBytes, {
      contentType: 'application/pdf',
      upsert: true,
    });

  if (uploadError) {
    console.error('Upload error:', uploadError);
    return null;
  }

  const { data: signed } = await supabase.storage
    .from('signed-contracts')
    .createSignedUrl(path, 60 * 60 * 24 * 30);

  const pdfUrl = signed?.signedUrl || path;

  await supabase.from('signing_links').update({ pdf_url: pdfUrl }).eq('id', id);

  return pdfUrl;
}
